### ISSUE TITLE
exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by n8behavior** [hashicorp/docker-hub-images#13] opened 2016-08-05 18:36 UTC
```
$ docker run -i -t hashicorp/terraform:light terraform
standard_init_linux.go:175: exec user process caused "no such file or directory"
```

My system

```
$ docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 23
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.57 GiB
Name: jackbox
ID: NWSH:ZHPA:KETS:UIKE:AMTZ:G2HJ:NOS3:TUKP:CUM3:Q4OD:W3GO:DDEJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

This a physical machine. Also, same error using Macbook and Docker for Mac

**Comment by timfallmk** [comment] 2016-08-12 20:06
Duplicate of #7 . Should be fixed now.

**Comment by catsby** [comment] 2016-12-14 14:28
Sorry for the trouble, but this now works. Thanks!

**Closed by catsby** 2016-12-14 14:28 UTC
